# Generated by Django 2.2 on 2021-03-10 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('venue', models.CharField(max_length=255)),
                ('show_date', models.DateTimeField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tickets', models.CharField(max_length=255, null=True)),
                ('details', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
