# Generated by Django 2.2 on 2021-03-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_announcements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('stage_name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=60)),
                ('hometown', models.CharField(max_length=255, null=True)),
                ('genre', models.CharField(max_length=100, null=True)),
                ('website', models.CharField(max_length=255, null=True)),
                ('photo', models.FileField(null=True, upload_to='')),
                ('likes', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
