# Generated by Django 2.2 on 2021-03-16 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0003_artist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcements',
            old_name='post',
            new_name='ann_post',
        ),
        migrations.AddField(
            model_name='announcements',
            name='ann_posted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ann_added', to='artist.Artist'),
        ),
    ]
