# Generated by Django 2.2 on 2021-03-17 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0004_auto_20210316_1039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='city',
            new_name='location',
        ),
        migrations.AddField(
            model_name='tour',
            name='show_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='tour_posted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tour_added', to='artist.Artist'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='details',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tickets',
            field=models.TextField(null=True),
        ),
    ]
