# Generated by Django 2.2 on 2021-03-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0006_artist_followed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='followed_by',
            field=models.ManyToManyField(related_name='artist_followed_by', to='fan.Fan'),
        ),
    ]
