# Generated by Django 2.2 on 2021-03-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fan', '0001_initial'),
        ('artist', '0007_auto_20210318_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='attendee',
            field=models.ManyToManyField(related_name='rsvp_by', to='fan.Fan'),
        ),
    ]
