# Generated by Django 2.2 on 2021-03-18 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0008_tour_attendee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='tour_posted_by',
            new_name='tour_added_by',
        ),
    ]
