# Generated by Django 2.2 on 2021-03-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0009_auto_20210318_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='show_time',
            field=models.TimeField(null=True),
        ),
    ]
