# Generated by Django 2.2 on 2021-03-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fan', '0001_initial'),
        ('artist', '0011_auto_20210319_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='likes',
            field=models.ManyToManyField(related_name='liked_by', to='fan.Fan'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
