# Generated by Django 2.2 on 2021-03-22 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0012_auto_20210320_0643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='likes',
        ),
    ]
