# Generated by Django 2.2 on 2021-03-22 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0013_remove_artist_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='bio',
            field=models.TextField(null=True),
        ),
    ]
